---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  creationTimestamp: null
  name: loadbalancers.loadbalancer.harvesterhci.io
spec:
  group: loadbalancer.harvesterhci.io
  names:
    kind: LoadBalancer
    listKind: LoadBalancerList
    plural: loadbalancers
    shortNames:
    - lb
    - lbs
    singular: loadbalancer
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.description
      name: DESCRIPTION
      type: string
    - jsonPath: .spec.ipam
      name: IPAM
      type: string
    - jsonPath: .status.address
      name: ADDRESS
      type: string
    deprecated: true
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendServers:
                description: The LB for Harvester is different from common lb because
                  all listeners have the same backend servers.
                items:
                  type: string
                type: array
              description:
                type: string
              healthCheck:
                properties:
                  PeriodSeconds:
                    description: 'TODO: The first letter is uppercase, which is inconsistent
                      with the k8s API.'
                    type: integer
                  failureThreshold:
                    type: integer
                  port:
                    type: integer
                  successThreshold:
                    type: integer
                  timeoutSeconds:
                    type: integer
                required:
                - PeriodSeconds
                - failureThreshold
                - port
                - successThreshold
                - timeoutSeconds
                type: object
              ipam:
                enum:
                - pool
                - dhcp
                type: string
              listeners:
                items:
                  properties:
                    backendPort:
                      format: int32
                      type: integer
                    name:
                      type: string
                    port:
                      format: int32
                      type: integer
                    protocol:
                      default: TCP
                      type: string
                  required:
                  - name
                  - port
                  - protocol
                  type: object
                type: array
            required:
            - ipam
            type: object
          status:
            properties:
              address:
                type: string
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    lastUpdateTime:
                      description: The last time this condition was updated.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of the condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: false
    subresources: {}
  - additionalPrinterColumns:
    - jsonPath: .spec.description
      name: DESCRIPTION
      type: string
    - jsonPath: .spec.workloadType
      name: WORKLOADTYPE
      type: string
    - jsonPath: .spec.ipam
      name: IPAM
      type: string
    - jsonPath: .status.address
      name: ADDRESS
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendServerSelector:
                additionalProperties:
                  items:
                    type: string
                  type: array
                type: object
              description:
                type: string
              healthCheck:
                properties:
                  failureThreshold:
                    type: integer
                  periodSeconds:
                    type: integer
                  port:
                    type: integer
                  successThreshold:
                    type: integer
                  timeoutSeconds:
                    type: integer
                type: object
              ipPool:
                type: string
              ipam:
                enum:
                - pool
                - dhcp
                type: string
              listeners:
                items:
                  properties:
                    backendPort:
                      format: int32
                      type: integer
                    name:
                      type: string
                    port:
                      format: int32
                      type: integer
                    protocol:
                      default: TCP
                      type: string
                  required:
                  - backendPort
                  - port
                  - protocol
                  type: object
                type: array
              workloadType:
                enum:
                - vm
                - cluster
                type: string
            type: object
          status:
            properties:
              address:
                type: string
              allocatedAddress:
                properties:
                  gateway:
                    type: string
                  ip:
                    type: string
                  ipPool:
                    type: string
                  mask:
                    type: string
                type: object
              backendServers:
                items:
                  type: string
                type: array
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    lastUpdateTime:
                      description: The last time this condition was updated.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of the condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources: {}
