#!/bin/bash
set -e

TOP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
SCRIPTS_DIR="${TOP_DIR}/scripts"
PACKAGE_DIR="${TOP_DIR}/package"

source "${SCRIPTS_DIR}"/version

ARCH=${ARCH:-"amd64"}
SUFFIX="-${ARCH}"

cd $(dirname $0)/..

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

IMAGE=${REPO}/harvester-load-balancer:${TAG}
IMAGE_WEBHOOK=${REPO}/harvester-load-balancer-webhook:${TAG}
DOCKERFILE=${PACKAGE_DIR}/Dockerfile
DOCKERFILE_WEBHOOK=${PACKAGE_DIR}/Dockerfile.webhook
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
    DOCKERFILE_WEBHOOK=${DOCKERFILE_WEBHOOK}.${ARCH}
fi

echo "Building image ${IMAGE}"

docker build -f ${DOCKERFILE} -t ${IMAGE} .

echo "Building image ${IMAGE_WEBHOOK}"

docker build -f ${DOCKERFILE_WEBHOOK} -t ${IMAGE_WEBHOOK} .
