#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:-"amd64"}
SUFFIX="-${ARCH}"

cd $(dirname $0)/..

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

mkdir -p dist/artifacts
cp bin/harvester-load-balancer${SUFFIX} dist/artifacts/harvester-load-balancer${SUFFIX}
cp bin/harvester-load-balancer-webhook${SUFFIX} dist/artifacts/harvester-load-balancer-webhook${SUFFIX}

IMAGE=${REPO}/harvester-load-balancer:${TAG}
IMAGE_WEBHOOK=${REPO}/harvester-load-balancer-webhook:${TAG}
DOCKERFILE=package/Dockerfile
DOCKERFILE_WEBHOOK=package/Dockerfile.webhook
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
    DOCKERFILE_WEBHOOK=${DOCKERFILE_WEBHOOK}.${ARCH}
fi

buildx build --load \
    -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}

buildx build --load \
    -f ${DOCKERFILE_WEBHOOK} -t ${IMAGE_WEBHOOK} .
echo Built ${IMAGE_WEBHOOK}
